export interface Contract {
  id: number
  name: string
  nameEn: string
  nameLo: string
  totalValue: string
  thudoValue: string
  startDate: string
  completionDate: string
  status: string
  statusEn: string
  statusLo: string
}

export const contractsData: Contract[] = [
  {
    id: 1,
    name: "Cung cấp và lắp đặt thiết bị xử lý nước sinh hoạt (430 m³/ngày & 510 m³/ngày)",
    nameEn: "Supply and Installation of Domestic Water Treatment Equipment (430 m³/day & 510 m³/day)",
    nameLo: "ການສະໜອງ ແລະ ຕິດຕັ້ງອຸປະກອນບຳບັດນ້ຳປະປາ (430 m³/ວັນ & 510 m³/ວັນ)",
    totalValue: "4.829 tỷ VND (~185,570 USD)",
    thudoValue: "4.829 tỷ VND (~185,570 USD)",
    startDate: "04/2025",
    completionDate: "Ongoing",
    status: "Đang thực hiện",
    statusEn: "In Progress",
    statusLo: "ກຳລັງດຳເນີນການ",
  },
  {
    id: 2,
    name: "Tư vấn báo cáo nghiên cứu khả thi, thiết kế cơ sở, báo cáo thủy văn, thiết kế bản vẽ thi công – Dự án: Hệ thống cấp nước thô cho chuỗi đô thị dọc Quốc lộ 47, Thanh Hóa",
    nameEn: "Consulting on Feasibility Study Report, Basic Design, Hydrological Report, and Construction Drawing Design – Project: Raw Water Supply System for Urban Chain along Quốc lộ 47, Thanh Hóa",
    nameLo: "ການໃຫ້ຄຳປຶກສາບົດລາຍງານການສຶກສາຄວາມເປັນໄປໄດ້, ການອອກແບບຂັ້ນພື້ນຖານ, ບົດລາຍງານອຸທົກກະສາດ, ແລະ ການອອກແບບແຕ້ມແບບກໍ່ສ້າງ – ໂຄງການ: ລະບົບສະໜອງນ້ຳດິບ ສຳລັບຕ່ອງໂສ້ຕົວເມືອງ ຕາມເສັ້ນທາງ Quốc lộ 47, Thanh Hóa",
    totalValue: "5.966 tỷ VND (~240,000 USD)",
    thudoValue: "5.966 tỷ VND (~240,000 USD)",
    startDate: "09/2024",
    completionDate: "Ongoing",
    status: "Đang thực hiện",
    statusEn: "In Progress",
    statusLo: "ກຳລັງດຳເນີນການ",
  },
  {
    id: 3,
    name: "Tư vấn khảo sát, báo cáo nghiên cứu khả thi, thiết kế bản vẽ thi công – Dự án: Hệ thống cấp nước thô Bim Sơn, Thanh Hóa",
    nameEn: "Consulting on Survey, Feasibility Study Report, and Construction Drawing Design – Project: Raw Water Supply System in Bỉm Sơn, Thanh Hóa",
    nameLo: "精度ການໃຫ້ຄຳປຶກສາການສຳຫຼວດ, ບົດລາຍງານການສຶກສາຄວາມເປັນໄປໄດ້, ແລະ ການອອກແບບແຕ້ມແບບກໍ່ສ້າງ – ໂຄງການ: ລະບົບສະໜອງນ້ຳດິບ Bỉm Sơn, Thanh Hóa",
    totalValue: "6.748 tỷ VND (~293,000 USD)",
    thudoValue: "6.748 tỷ VND (~293,000 USD)",
    startDate: "05/2021",
    completionDate: "Ongoing",
    status: "Đang thực hiện",
    statusEn: "In Progress",
    statusLo: "ກຳລັງດຳເນີນການ",
  },
  {
    id: 4,
    name: "Tư vấn thiết kế bản vẽ thi công và dự toán chi tiết – Nâng cấp hệ thống phòng chống xâm nhập mặn An Trạch (210.000 → 420.000 m³/ngày)",
    nameEn: "Consulting on Construction Drawing Design and Detailed Cost Estimate – Upgrading An Trạch Raw Water System (210,000 → 420,000 m³/day)",
    nameLo: "ການໃຫ້ຄຳປຶກສາການອອກແບບແຕ້ມແບບກໍ່ສ້າງ ແລະ ການປະເມີນລາຄາລະອຽດ – ການຍົກລະດັບລະບົບນ້ຳດິບ An Trạch (210.000 → 420.000 m³/ວັນ)",
    totalValue: "3.157 tỷ VND (~137,000 USD)",
    thudoValue: "3.157 tỷ VND (~137,000 USD)",
    startDate: "09/2020",
    completionDate: "11/2020",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 5,
    name: "Tư vấn thiết kế, bản vẽ thi công và dự toán – Dự án nhà máy nước Quảng Ngãi",
    nameEn: "Consulting on Design, Construction Drawings and Estimates – Quảng Ngãi Water Plant Project",
    nameLo: "ການໃຫ້ຄຳປຶກສາການອອກແບບ, ແຕ້ມແບບກໍ່ສ້າງ ແລະ ການປະເມີນລາຄາ – ໂຄງການໂຮງງານຜະລິດນ້ຳປະປາ Quảng Ngãi",
    totalValue: "500 triệu VND (~20,800 USD)",
    thudoValue: "500 triệu VND (~20,800 USD)",
    startDate: "07/2022",
    completionDate: "12/2022",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 6,
    name: "Tư vấn khảo sát địa hình và địa chất, thiết kế – Nhà máy nước sạch (20.000 m³/ngày), Kon Tum",
    nameEn: "Consulting on Topographic Survey and Design – Clean Water Plant (20,000 m³/day), Kon Tum",
    nameLo: "ການໃຫ້ຄຳປຶກສາການສຳຫຼວດພູມສັນຖານ ແລະ ທໍລະນີສາດ, ການອອກແບບ – ໂຮງງານຜະລິດນ້ຳສະອາດ (20.000 m³/ວັນ), Kon Tum",
    totalValue: "2.400 tỷ VND (~100,000 USD)",
    thudoValue: "2.400 tỷ VND (~100,000 USD)",
    startDate: "12/2024",
    completionDate: "In progress",
    status: "Đang thực hiện",
    statusEn: "In Progress",
    statusLo: "ກຳລັງດຳເນີນການ",
  },
  {
    id: 7,
    name: "Thiết kế, dự toán – Nhà máy nước sạch An Sinh (9.000 m³/ngày)",
    nameEn: "Design and Estimate – Clean Water Plant in An Sinh Commune (9,000 m³/day)",
    nameLo: "ການອອກແບບ ແລະ ການປະເມີນລາຄາ – ໂຮງງານຜະລິດນ້ຳສະອາດ An Sinh (9.000 m³/ວັນ)",
    totalValue: "930 triệu VND (~40,000 USD)",
    thudoValue: "930 triệu VND (~40,000 USD)",
    startDate: "12/2024",
    completionDate: "In progress",
    status: "Đang thực hiện",
    statusEn: "In Progress",
    statusLo: "ກຳລັງດຳເນີນການ",
  },
  {
    id: 8,
    name: "Khảo sát địa chất, thủy văn, báo cáo nghiên cứu khả thi, thiết kế – Nhà máy nước Phú Bình (30.000 m³/ngày)",
    nameEn: "Geological and Hydrological Survey, Feasibility Study, and Design – Phú Bình Water Plant (30,000 m³/day)",
    nameLo: "ການສຳຫຼວດທໍລະນີສາດ ແລະ ອຸທົກກະສາດ, ການສຶກສາຄວາມເປັນໄປໄດ້, ແລະ ການອອກແບບ – ໂຮງງານຜະລິດນ້ຳປະປາ Phú Bình (30.000 m³/ວັນ)",
    totalValue: "2.267 tỷ VND (~90,000 USD)",
    thudoValue: "2.267 tỷ VND (~90,000 USD)",
    startDate: "02/2023",
    completionDate: "02/2024",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 9,
    name: "Khảo sát và thiết kế đường ống nước thô – Mở rộng nhà máy nước sạch (20.000 m³/ngày), Kon Tum",
    nameEn: "Survey and Design for Raw Water Pipelines – Expansion of Clean Water Plant (20,000 m³/day), Kon Tum",
    nameLo: "ການສຳຫຼວດ ແລະ ອອກແບບທໍ່ສົ່ງນ້ຳດິບ – ການຂະຫຍາຍໂຮງງານຜະລິດນ້ຳສະອາດ (20.000 m³/ວັນ), Kon Tum",
    totalValue: "631 triệu VND (~25,000 USD)",
    thudoValue: "631 triệu VND (~25,000 USD)",
    startDate: "04/2022",
    completionDate: "09/2022",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 10,
    name: "Tư vấn chính sách đầu tư và thiết kế sơ bộ – Dự án nhà máy nước Đông Hà Sông (100.000 m³/ngày), Quảng Nam",
    nameEn: "Investment Policy Advisory and Preliminary Design – Đông Hà Sông Water Plant Project (100,000 m³/day), Quảng Nam",
    nameLo: "ການໃຫ້ຄຳປຶກສານະໂຍບາຍການລົງທຶນ ແລະ ການອອກແບບເບື້ອງຕົ້ນ – ໂຄງການໂຮງງານຜະລິດນ້ຳປະປາ Đông Hà Sông (100.000 m³/ວັນ), Quảng Nam",
    totalValue: "2.147 tỷ VND (~93,126 USD)",
    thudoValue: "2.147 tỷ VND (~93,126 USD)",
    startDate: "04/2021",
    completionDate: "07/2021",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 11,
    name: "Báo cáo nghiên cứu khả thi – Đường ống truyền tải nước vùng phía Bắc tỉnh Hưng Yên",
    nameEn: "Feasibility Study – Water Transmission Pipeline for Northern Hưng Yên",
    nameLo: "ບົດລາຍງານການສຶກສາຄວາມເປັນໄປໄດ້ – ທໍ່ສົ່ງນ້ຳປະປາສຳລັບເຂດພາກເໜືອ Hưng Yên",
    totalValue: "1.100 tỷ VND (~45,800 USD)",
    thudoValue: "880 triệu VND (~36,600 USD)",
    startDate: "03/2021",
    completionDate: "06/2021",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 12,
    name: "Báo cáo nghiên cứu khả thi và tổng đầu tư – Nâng cấp hệ thống cấp nước thô An Trạch (210.000 → 420.000 m³/ngày)",
    nameEn: "Feasibility Study and Total Investment – Upgrading An Trạch Raw Water System (210,000 → 420,000 m³/day)",
    nameLo: "ບົດລາຍງານການສຶກສາຄວາມເປັນໄປໄດ້ ແລະ ມູນຄ່າການລົງທຶນລວມ – ການຍົກລະດັບລະບົບນ້ຳດິບ An Trạch (210.000 → 420.000 m³/ວັນ)",
    totalValue: "500 triệu VND (~25,000 USD)",
    thudoValue: "500 triệu VND (~25,000 USD)",
    startDate: "09/2019",
    completionDate: "12/2019",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 13,
    name: "Báo cáo kỹ thuật và thiết kế bản vẽ thi công – Tăng công suất nhà máy nước Cầu Đỏ (210.000 → 290.000 m³/ngày)",
    nameEn: "Technical Report and Construction Drawing Design – Increasing Capacity of Cầu Đỏ Water Plant (210,000 → 290,000 m³/day)",
    nameLo: "ບົດລາຍງານເຕັກນິກ ແລະ ການອອກແບບແຕ້ມແບບກໍ່ສ້າງ – ການເພີ່ມກຳລັງການຜະລິດໂຮງງານຜະລິດນ້ຳປະປາ Cầu Đỏ (210.000 → 290.000 m³/ວັນ)",
    totalValue: "1.2 tỷ VND (~55,000 USD)",
    thudoValue: "1.2 tỷ VND (~55,000 USD)",
    startDate: "01/2019",
    completionDate: "04/2019",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 14,
    name: "Thiết kế, dự toán – Tăng công suất nhà máy nước Cầu Đỏ (Giai đoạn 1: 60.000 m³/ngày)",
    nameEn: "Design and Estimate – Increasing Capacity of Cầu Đỏ Water Treatment Plant (Phase 1: 60,000 m³/day)",
    nameLo: "ການອອກແບບ ແລະ ການປະເມີນລາຄາ – ການເພີ່ມກຳລັງການຜະລິດໂຮງງານຜະລິດນ້ຳປະປາ Cầu Đỏ (ໄລຍະທີ 1: 60.000 m³/ວັນ)",
    totalValue: "2.4 tỷ VND (~120,000 USD)",
    thudoValue: "2.4 tỷ VND (~120,000 USD)",
    startDate: "09/2017",
    completionDate: "10/2017",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 15,
    name: "Thiết kế trạm bơm điều tiết Tây Mỗ (300.000 m³/ngày)",
    nameEn: "Design of Tây Mỗ Regulating Station (300,000 m³/day)",
    nameLo: "ການອອກແບບສະຖານີຈັກສູບນ້ຳປັບລະດັບ Tây Mỗ (300.000 m³/ວັນ)",
    totalValue: "5.23 tỷ VND (~240,000 USD)",
    thudoValue: "540 triệu VND (~25,000 USD)",
    startDate: "01/2018",
    completionDate: "05/2018",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
  {
    id: 16,
    name: "Báo cáo dự án đầu tư – Xây dựng nhà máy nước Hòa Liên (120.000 m³/ngày)",
    nameEn: "Investment Project Report – Construction of Hòa Liên Water Plant (120,000 m³/day)",
    nameLo: "ບົດລາຍງານໂຄງການລົງທຶນ – ການກໍ່ສ້າງໂຮງງານຜະລິດນ້ຳປະປາ Hòa Liên (120.000 m³/ວັນ)",
    totalValue: "1.1 tỷ VND (~55,000 USD)",
    thudoValue: "0.45 tỷ VND (~22,000 USD)",
    startDate: "06/2017",
    completionDate: "12/2017",
    status: "Hoàn thành",
    statusEn: "Completed",
    statusLo: "ສຳເລັດແລ້ວ",
  },
]

export const getContractsByLanguage = (lang: "vi" | "en" | "lo") => {
  return contractsData
    .sort((a, b) => {
      const dateA = new Date(a.startDate.replace(/(\d{2})\/(\d{4})/, "$2-$1-01"))
      const dateB = new Date(b.startDate.replace(/(\d{2})\/(\d{4})/, "$2-$1-01"))
      return dateB.getTime() - dateA.getTime()
    })
    .map((contract) => ({
      ...contract,
      name: lang === "vi" ? contract.name : lang === "en" ? contract.nameEn : contract.nameLo.replace("精度", ""),
      status: lang === "vi" ? contract.status : lang === "en" ? contract.statusEn : contract.statusLo,
    }))
}
